/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LatihanGUI;

/**
 *
 * @author ASUS
 */
public class kalkulator extends javax.swing.JFrame {
    String angka="";
    double jumlah,angka1,angka2;
    int pilih;
    public kalkulator() {
        initComponents();
        String angka;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Hasil = new javax.swing.JTextField();
        CE = new javax.swing.JButton();
        C = new javax.swing.JButton();
        Hapus = new javax.swing.JButton();
        Akar = new javax.swing.JButton();
        Plusminus = new javax.swing.JButton();
        Kali = new javax.swing.JButton();
        Sembilan = new javax.swing.JButton();
        Delapan = new javax.swing.JButton();
        Tujuh = new javax.swing.JButton();
        Empat = new javax.swing.JButton();
        Lima = new javax.swing.JButton();
        Enam = new javax.swing.JButton();
        Kurang = new javax.swing.JButton();
        Persen = new javax.swing.JButton();
        Xkuadrat = new javax.swing.JButton();
        Nol = new javax.swing.JButton();
        Tambah = new javax.swing.JButton();
        Tiga = new javax.swing.JButton();
        Dua = new javax.swing.JButton();
        Satu = new javax.swing.JButton();
        Samadengan = new javax.swing.JButton();
        Bagi = new javax.swing.JButton();
        Koma = new javax.swing.JButton();
        Plusminus1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        jPanel24 = new javax.swing.JPanel();
        jPanel25 = new javax.swing.JPanel();
        jPanel26 = new javax.swing.JPanel();
        jPanel27 = new javax.swing.JPanel();
        jPanel28 = new javax.swing.JPanel();
        jPanel29 = new javax.swing.JPanel();
        jPanel30 = new javax.swing.JPanel();
        jPanel31 = new javax.swing.JPanel();
        jPanel32 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kalkulator");
        setResizable(false);
        getContentPane().setLayout(null);

        Hasil.setEditable(false);
        getContentPane().add(Hasil);
        Hasil.setBounds(12, 12, 380, 108);

        CE.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        CE.setText("CE");
        CE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CEActionPerformed(evt);
            }
        });
        getContentPane().add(CE);
        CE.setBounds(10, 220, 80, 60);

        C.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        C.setText("C");
        C.setToolTipText("");
        C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CActionPerformed(evt);
            }
        });
        getContentPane().add(C);
        C.setBounds(110, 220, 80, 60);

        Hapus.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        Hapus.setText("Hapus");
        Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusActionPerformed(evt);
            }
        });
        getContentPane().add(Hapus);
        Hapus.setBounds(210, 220, 80, 60);

        Akar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        Akar.setText("√");
        Akar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AkarActionPerformed(evt);
            }
        });
        getContentPane().add(Akar);
        Akar.setBounds(210, 150, 80, 60);

        Plusminus.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        Plusminus.setText("+/-");
        Plusminus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlusminusActionPerformed(evt);
            }
        });
        getContentPane().add(Plusminus);
        Plusminus.setBounds(10, 500, 80, 60);

        Kali.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        Kali.setText("x");
        Kali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KaliActionPerformed(evt);
            }
        });
        getContentPane().add(Kali);
        Kali.setBounds(310, 220, 80, 60);

        Sembilan.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        Sembilan.setText("9");
        Sembilan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SembilanActionPerformed(evt);
            }
        });
        getContentPane().add(Sembilan);
        Sembilan.setBounds(210, 290, 80, 60);

        Delapan.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        Delapan.setText("8");
        Delapan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DelapanActionPerformed(evt);
            }
        });
        getContentPane().add(Delapan);
        Delapan.setBounds(110, 290, 80, 60);

        Tujuh.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        Tujuh.setText("7");
        Tujuh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TujuhActionPerformed(evt);
            }
        });
        getContentPane().add(Tujuh);
        Tujuh.setBounds(10, 290, 80, 60);

        Empat.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        Empat.setText("4");
        Empat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpatActionPerformed(evt);
            }
        });
        getContentPane().add(Empat);
        Empat.setBounds(10, 360, 80, 60);

        Lima.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        Lima.setText("5");
        Lima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimaActionPerformed(evt);
            }
        });
        getContentPane().add(Lima);
        Lima.setBounds(110, 360, 80, 60);

        Enam.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        Enam.setText("6");
        Enam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnamActionPerformed(evt);
            }
        });
        getContentPane().add(Enam);
        Enam.setBounds(210, 360, 80, 60);

        Kurang.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        Kurang.setText("-");
        Kurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KurangActionPerformed(evt);
            }
        });
        getContentPane().add(Kurang);
        Kurang.setBounds(310, 290, 80, 60);

        Persen.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        Persen.setText("%");
        Persen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PersenActionPerformed(evt);
            }
        });
        getContentPane().add(Persen);
        Persen.setBounds(10, 150, 80, 60);

        Xkuadrat.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        Xkuadrat.setText("x^2");
        Xkuadrat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XkuadratActionPerformed(evt);
            }
        });
        getContentPane().add(Xkuadrat);
        Xkuadrat.setBounds(110, 150, 80, 60);

        Nol.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        Nol.setText("0");
        Nol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NolActionPerformed(evt);
            }
        });
        getContentPane().add(Nol);
        Nol.setBounds(110, 500, 80, 60);

        Tambah.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        Tambah.setText("+");
        Tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahActionPerformed(evt);
            }
        });
        getContentPane().add(Tambah);
        Tambah.setBounds(310, 360, 80, 60);

        Tiga.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        Tiga.setText("3");
        Tiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TigaActionPerformed(evt);
            }
        });
        getContentPane().add(Tiga);
        Tiga.setBounds(210, 430, 80, 60);

        Dua.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        Dua.setText("2");
        Dua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DuaActionPerformed(evt);
            }
        });
        getContentPane().add(Dua);
        Dua.setBounds(110, 430, 80, 60);

        Satu.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        Satu.setText("1");
        Satu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SatuActionPerformed(evt);
            }
        });
        getContentPane().add(Satu);
        Satu.setBounds(10, 430, 80, 60);

        Samadengan.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        Samadengan.setText("=");
        Samadengan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SamadenganActionPerformed(evt);
            }
        });
        getContentPane().add(Samadengan);
        Samadengan.setBounds(310, 430, 80, 130);

        Bagi.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        Bagi.setText(":");
        Bagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BagiActionPerformed(evt);
            }
        });
        getContentPane().add(Bagi);
        Bagi.setBounds(310, 150, 80, 60);

        Koma.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        Koma.setText(".");
        Koma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KomaActionPerformed(evt);
            }
        });
        getContentPane().add(Koma);
        Koma.setBounds(210, 500, 80, 60);

        Plusminus1.setBackground(new java.awt.Color(255, 0, 0));
        Plusminus1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Plusminus1.setText("Close");
        Plusminus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Plusminus1ActionPerformed(evt);
            }
        });
        getContentPane().add(Plusminus1);
        Plusminus1.setBounds(310, 570, 80, 30);

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jPanel5);
        jPanel5.setBounds(-10, 550, 110, 100);

        jPanel6.setBackground(new java.awt.Color(102, 102, 102));
        getContentPane().add(jPanel6);
        jPanel6.setBounds(0, 370, 100, 90);

        jPanel7.setBackground(new java.awt.Color(102, 102, 102));
        getContentPane().add(jPanel7);
        jPanel7.setBounds(100, 460, 100, 90);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        getContentPane().add(jPanel1);
        jPanel1.setBounds(200, 550, 100, 100);

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 280, 100, 90);

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        getContentPane().add(jPanel3);
        jPanel3.setBounds(100, 370, 100, 90);

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));
        getContentPane().add(jPanel4);
        jPanel4.setBounds(200, 460, 100, 90);

        jPanel8.setBackground(new java.awt.Color(153, 153, 153));
        getContentPane().add(jPanel8);
        jPanel8.setBounds(300, 550, 110, 110);

        jPanel9.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(jPanel9);
        jPanel9.setBounds(0, 190, 100, 90);

        jPanel10.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(jPanel10);
        jPanel10.setBounds(100, 280, 100, 90);

        jPanel11.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(jPanel11);
        jPanel11.setBounds(200, 370, 100, 90);

        jPanel12.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(jPanel12);
        jPanel12.setBounds(300, 460, 120, 90);

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jPanel13);
        jPanel13.setBounds(300, 370, 110, 90);

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jPanel14);
        jPanel14.setBounds(200, 280, 100, 90);

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jPanel15);
        jPanel15.setBounds(100, 190, 100, 90);

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jPanel16);
        jPanel16.setBounds(0, 100, 100, 90);

        jPanel17.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(jPanel17);
        jPanel17.setBounds(100, 100, 100, 90);

        jPanel18.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(jPanel18);
        jPanel18.setBounds(0, 10, 100, 90);

        jPanel19.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(jPanel19);
        jPanel19.setBounds(200, 190, 100, 90);

        jPanel20.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(jPanel20);
        jPanel20.setBounds(300, 280, 110, 90);

        jPanel21.setBackground(new java.awt.Color(153, 153, 153));
        getContentPane().add(jPanel21);
        jPanel21.setBounds(300, 190, 110, 90);

        jPanel22.setBackground(new java.awt.Color(153, 153, 153));
        getContentPane().add(jPanel22);
        jPanel22.setBounds(200, 100, 100, 90);

        jPanel23.setBackground(new java.awt.Color(153, 153, 153));
        getContentPane().add(jPanel23);
        jPanel23.setBounds(100, 10, 100, 90);

        jPanel24.setBackground(new java.awt.Color(153, 153, 153));
        getContentPane().add(jPanel24);
        jPanel24.setBounds(-10, -10, 110, 20);

        jPanel25.setBackground(new java.awt.Color(102, 102, 102));
        getContentPane().add(jPanel25);
        jPanel25.setBounds(300, 100, 110, 90);

        jPanel26.setBackground(new java.awt.Color(102, 102, 102));
        getContentPane().add(jPanel26);
        jPanel26.setBounds(200, 10, 100, 90);

        jPanel27.setBackground(new java.awt.Color(102, 102, 102));
        getContentPane().add(jPanel27);
        jPanel27.setBounds(100, -10, 100, 20);

        jPanel28.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jPanel28);
        jPanel28.setBounds(300, -10, 110, 20);

        jPanel29.setBackground(new java.awt.Color(51, 51, 51));
        getContentPane().add(jPanel29);
        jPanel29.setBounds(300, 10, 100, 90);

        jPanel30.setBackground(new java.awt.Color(51, 51, 51));
        getContentPane().add(jPanel30);
        jPanel30.setBounds(200, 0, 100, 100);

        jPanel31.setBackground(new java.awt.Color(51, 51, 51));
        getContentPane().add(jPanel31);
        jPanel31.setBounds(0, 460, 100, 90);

        jPanel32.setBackground(new java.awt.Color(51, 51, 51));
        getContentPane().add(jPanel32);
        jPanel32.setBounds(100, 550, 100, 100);

        setSize(new java.awt.Dimension(417, 651));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CEActionPerformed
        // TODO add your handling code here:
        Hasil.setText("");
        angka1=0.0;
        angka="";
    }//GEN-LAST:event_CEActionPerformed

    private void CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CActionPerformed
        // TODO add your handling code here:
        Hasil.setText("");
        angka1=0.0;
        angka2=0.0;
        jumlah=0.0;
        angka="";
    }//GEN-LAST:event_CActionPerformed

    private void HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusActionPerformed
        // TODO add your handling code here:
        angka = angka.substring(0, angka.length()-1);
        Hasil.setText(angka);
    }//GEN-LAST:event_HapusActionPerformed

    private void AkarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AkarActionPerformed
        // TODO add your handling code here:
        angka1=Double.parseDouble(angka);
        Hasil.setText("√");
        angka="";
        pilih=5;
    }//GEN-LAST:event_AkarActionPerformed

    private void PlusminusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlusminusActionPerformed
        if(!angka.contains("-"))
            angka = "-"+angka;
        else
            angka = angka.substring(1, angka.length());
        Hasil.setText(angka);
        
    }//GEN-LAST:event_PlusminusActionPerformed

    private void KaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KaliActionPerformed
        // TODO add your handling code here:
        angka1=Double.parseDouble(angka);
        Hasil.setText("x");
        angka="";
        pilih=3;
    }//GEN-LAST:event_KaliActionPerformed

    private void SembilanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SembilanActionPerformed
        // TODO add your handling code here:
        angka += "9";
        Hasil.setText(angka);
    }//GEN-LAST:event_SembilanActionPerformed

    private void DelapanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DelapanActionPerformed
        // TODO add your handling code here:
        angka += "8";
        Hasil.setText(angka);
    }//GEN-LAST:event_DelapanActionPerformed

    private void TujuhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TujuhActionPerformed
        // TODO add your handling code here:
        angka += "7";
        Hasil.setText(angka);
    }//GEN-LAST:event_TujuhActionPerformed

    private void EmpatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpatActionPerformed
        // TODO add your handling code here:
        angka += "4";
        Hasil.setText(angka);
    }//GEN-LAST:event_EmpatActionPerformed

    private void LimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimaActionPerformed
        // TODO add your handling code here:
        angka += "5";
        Hasil.setText(angka);
    }//GEN-LAST:event_LimaActionPerformed

    private void EnamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnamActionPerformed
        // TODO add your handling code here:
        angka += "6";
        Hasil.setText(angka);
    }//GEN-LAST:event_EnamActionPerformed

    private void KurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KurangActionPerformed
        // TODO add your handling code here:
        angka1=Double.parseDouble(angka);
        Hasil.setText("-");
        angka="";
        pilih=2;
    }//GEN-LAST:event_KurangActionPerformed

    private void PersenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PersenActionPerformed
        // TODO add your handling code here:
        angka1=Double.parseDouble(angka);
        Hasil.setText("%");
        angka="";
        pilih=7;
    }//GEN-LAST:event_PersenActionPerformed

    private void XkuadratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XkuadratActionPerformed
        // TODO add your handling code here:
        angka1=Double.parseDouble(angka);
        Hasil.setText("^");
        angka="";
        pilih=6;
        
    }//GEN-LAST:event_XkuadratActionPerformed

    private void TambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahActionPerformed
        // TODO add your handling code here:
        angka1=Double.parseDouble(angka);
        Hasil.setText("+");
        angka="";
        pilih=1;
    }//GEN-LAST:event_TambahActionPerformed

    private void TigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TigaActionPerformed
        // TODO add your handling code here:
        angka += "3";
        Hasil.setText(angka);
    }//GEN-LAST:event_TigaActionPerformed

    private void DuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DuaActionPerformed
        // TODO add your handling code here:
        angka += "2";
        Hasil.setText(angka);
    }//GEN-LAST:event_DuaActionPerformed

    private void SatuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SatuActionPerformed
        // TODO add your handling code here:
        angka += "1";
        Hasil.setText(angka);
    }//GEN-LAST:event_SatuActionPerformed

    private void NolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NolActionPerformed
        // TODO add your handling code here:
        angka += "0";
        Hasil.setText(angka);
    }//GEN-LAST:event_NolActionPerformed

    private void BagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BagiActionPerformed
        // TODO add your handling code here:
        angka1=Double.parseDouble(angka);
        Hasil.setText(":");
        angka="";
        pilih=5;
    }//GEN-LAST:event_BagiActionPerformed

    private void SamadenganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SamadenganActionPerformed
        // TODO add your handling code here:
        switch(pilih){

        case 1:
            angka2 = Double.parseDouble(angka);
            jumlah = angka1 + angka2;
            angka = Double.toString(jumlah);
            Hasil.setText(angka);
            break;
        case 2:
            angka2 = Double.parseDouble(angka);
            jumlah = angka1 - angka2;
            angka = Double.toString(jumlah);
            Hasil.setText(angka);
            break;
        case 3:
            angka2 = Double.parseDouble(angka);
            jumlah = angka1 * angka2;
            angka = Double.toString(jumlah);
            Hasil.setText(angka);
            break;
        case 4:
            angka2 = Double.parseDouble(angka);
            jumlah = angka1 / angka2;
            angka = Double.toString(jumlah);
            Hasil.setText(angka);
            break;
        case 5:
            jumlah = Math.sqrt(angka1);
                angka = Double.toString(jumlah);
                Hasil.setText(angka);
                break;
        case 6:
            jumlah = Math.pow(angka1, 2);
                angka = Double.toString(jumlah);
                Hasil.setText(angka);
                break;
        case 7:
            jumlah = angka1 / 100;
                angka = Double.toString(jumlah);
                Hasil.setText(angka);
                break;
        case 8:
            angka2 = Double.parseDouble(angka);
            jumlah = angka1 *1/(1) * angka2;
            angka = Double.toString(jumlah);
            Hasil.setText(angka);
            break;
        default:
            break;
        }
    }//GEN-LAST:event_SamadenganActionPerformed

    private void KomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KomaActionPerformed
        // TODO add your handling code here:
        angka += ".";
        Hasil.setText(angka);
    }//GEN-LAST:event_KomaActionPerformed

    private void Plusminus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Plusminus1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_Plusminus1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kalkulator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Akar;
    private javax.swing.JButton Bagi;
    private javax.swing.JButton C;
    private javax.swing.JButton CE;
    private javax.swing.JButton Delapan;
    private javax.swing.JButton Dua;
    private javax.swing.JButton Empat;
    private javax.swing.JButton Enam;
    private javax.swing.JButton Hapus;
    private javax.swing.JTextField Hasil;
    private javax.swing.JButton Kali;
    private javax.swing.JButton Koma;
    private javax.swing.JButton Kurang;
    private javax.swing.JButton Lima;
    private javax.swing.JButton Nol;
    private javax.swing.JButton Persen;
    private javax.swing.JButton Plusminus;
    private javax.swing.JButton Plusminus1;
    private javax.swing.JButton Samadengan;
    private javax.swing.JButton Satu;
    private javax.swing.JButton Sembilan;
    private javax.swing.JButton Tambah;
    private javax.swing.JButton Tiga;
    private javax.swing.JButton Tujuh;
    private javax.swing.JButton Xkuadrat;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
